---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_SERVER_URL: 'https://galaxy.ansible.com'

base_image:
  name: registry.redhat.io/ansible-automation-platform/ee-minimal-rhel9:latest

dependencies:
  galaxy:
    collections:
      - name: awx.awx
      - name: ansible.eda
      - name: community.general
      - name: ansible.posix
  python:
    - boto3
    - botocore
  system:
    - unzip [platform:rpm]
    - wget [platform:rpm]

additional_build_steps:
  prepend_galaxy:
    - ENV TERRAFORM_VERSION=1.7.5
  append_final:
    - RUN wget -q https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
    - RUN unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
    - RUN mv terraform /usr/local/bin/
    - RUN terraform --version
