---
- name: Drift Detection Rulebook
  hosts: all
  sources:
    - ansible.eda.watchdog:
        path: /etc/ssh/sshd_config
        recursive: false

  rules:
    - name: Detect SSH config change
      condition: event.change == "modified"
      action:
        run_job_template:
          name: "3 - Remediate Drift"
          organization: Default
